---
# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
extends: default

yaml-files:
  - .toolsharerc
  - .yamllint.yaml
  - '*.yaml'
  - '*.yml'
  - OWNERS_ALIASES
  - OWNERS

rules:
  document-start:
    level: error
  indentation: false
  line-length:
    max: 1200
    level: warning
  quoted-strings:
    quote-type: any
    required: only-when-needed
